Esri/arcgis-maps-sdk-unreal-engine-samples

sample_project/Content/SampleViewer/Samples/FeatureLayer/readme.md

**Sample**
**Summary**
It looks like the first line was a leftover of the Third Person sample readme...
**Tests**

Update first line of the readme

---

sample_project/Content/SampleViewer/Samples/Routing/readme.md

**Sample**
**Summary**
H1 title was missing
**Tests**

Add sample title line

---

README.md

**Sample**
**Summary**
Add Feature layer and Routing sample together with a minor fix
**Tests**

Add new samples

---

sample_project/Content/SampleViewer/Samples/Geocoding/readme.md

**Sample**
**Summary**
H1 title was missing
**Tests**

Add geocoding sample title

---

sample_project/Source/sample_project/Geocoding/Geocoder.cpp
sample_project/Source/sample_project/Geocoding/QueryLocation.h
sample_project/Source/sample_project/Routing/RouteManager.cpp

Fix the ability for the samples project to be built on MacOS.

Sam Fix mac build

---

sample_project/Content/SampleViewer/Samples/Routing/readme.md

**Sample**
Routing
**Summary**
Improve the readme content
**Tests**
Read it

Improve the readme content

---

templates/readme.md

Do you think this is too much info in a template?

Create readme template

---

sample_project/Content/SampleViewer/Samples/FeatureLayer/readme.md

**Sample**
Feature layer
**Summary**
Update the readme content
**Tests**
Read

Feature layer readme improvements

---

README.md

**Sample**
None
**Summary**
There are two samples that are currently not added to the list on the top readme.
**Tests**
read it
this is not a sample

Add missing sample to the list

---

README.md

**Summary**
Readme is updated to include links to our documentation for adding the plugin, and getting an API key.

Readme: Update formatting and instructions

---

README.md

Update README.md plugin version number

---

sample_project/Content/SampleViewer/Samples/HitTest/readme.md

Fix Readme

---

README.md

**Summary**
Updates readme to mention latest public release (1.4.0).
1.4.0

Update version to 1.4.0

---

xr_sample_project/xr_samplesproject.uproject

**Sample**
XR sample project 
**Summary**
Setting the  engine version to 5.4

Set the engine version for XR sample to 5.4

---

sample_project/Source/sample_project/WeatherQuery/WeatherQuery.h

**Sample**
Weather Sample
**Summary**
- Change the where clause so that more than 6 entries would should up in the drop down
**Tests**
Windows
Public version 1.6

Update Query Link Where Clause

---

README.md

Adding tabletop xr sample to readme.

Update README.md to have Tabletop XR Sample

---

sample_project/Source/sample_project.Target.cs
sample_project/Source/sample_project/3DAttribute/APIMapCreator.cpp
sample_project/Source/sample_project/Routing/RouteManager.cpp
sample_project/Source/sample_projectEditor.Target.cs

* Fix build issues and Weather Query bug
* Remove unused local variables
* Revert Weather Query files
* Fix Build issue for all supported UE Versions
**Sample**
**Checklist**
**Blueprints**

Update Release Branch

---

sample_project/Source/sample_project.Target.cs
sample_project/Source/sample_project/3DAttribute/APIMapCreator.cpp
sample_project/Source/sample_project/Routing/RouteManager.cpp
sample_project/Source/sample_projectEditor.Target.cs

N/A
- Update Release Branch with Main

Bug: Build issue with 5.4 (#108)

---

README.md
sample_project/sample_project.uproject
xr_sample_project/xr_samplesproject.uproject

**Sample**
Update Sample Project to 5.3
Update XR Sample Project to 5.5
**Checklist**
**Builds**
**Blueprints**
N/A
Daily Build 4417 with UE 5.3 & 5.5 for each respective Project

Quality of Life: Update sample project versions

---

README.md
sample_project/Content/SampleViewer/Samples/Flythrough/readme.md

Correct image link
Add Flythrough to main readme

Correct Flythru readme image and update main readme

---

sample_project/Content/SampleViewer/Samples/HitTest/readme.md

**Sample**
Hit Test readme
**Checklist**
**Blueprints**

Update readme.md remove apostrophe

---

sample_project/Content/SampleViewer/Samples/RealTime_Weather/readme.md

**Sample**
Missed this last PR, this one is a quick patch.
**Checklist**
**Blueprints**

Match title formats
